Ninja: build_log_perftest.cc File Reference
build_log_perftest.cc File Reference
#include <stdio.h>
#include <stdlib.h>
#include "build_log.h"
#include "graph.h"
#include "manifest_parser.h"
#include "state.h"
#include "util.h"
#include "metrics.h"
#include <unistd.h>
Functions
int main ()
bool WriteTestData (string *err)
Variables
const char kTestFilename [] = "BuildLogPerfTest-tempfile"
Function Documentation
int main ()
Definition at line 96 of file build_log_perftest.cc.
References GetTimeMillis(), kTestFilename, BuildLog::Load(), and WriteTestData().
bool WriteTestData (string * err)
Definition at line 31 of file build_log_perftest.cc.
References State::edges_, kTestFilename, BuildLog::OpenForWrite(), ManifestParser::ParseTest(), and BuildLog::RecordCommand().
Referenced by main().
Variable Documentation
const char kTestFilename[] = "BuildLogPerfTest-tempfile"
Definition at line 29 of file build_log_perftest.cc.
Referenced by main(), and WriteTestData().