Ninja: clean_test.cc File Reference
clean_test.cc File Reference
#include "clean.h"
#include "build.h"
#include "test.h"
Classes
struct CleanTest
Functions
TEST_F (CleanTest, CleanAll)
TEST_F (CleanTest, CleanAllDryRun)
TEST_F (CleanTest, CleanTarget)
TEST_F (CleanTest, CleanTargetDryRun)
TEST_F (CleanTest, CleanRule)
TEST_F (CleanTest, CleanRuleDryRun)
TEST_F (CleanTest, CleanRuleGenerator)
TEST_F (CleanTest, CleanDepFile)
TEST_F (CleanTest, CleanDepFileOnCleanTarget)
TEST_F (CleanTest, CleanDepFileOnCleanRule)
TEST_F (CleanTest, CleanRspFile)
TEST_F (CleanTest, CleanRsp)
TEST_F (CleanTest, CleanFailure)
TEST_F (CleanTest, CleanPhony)
Function Documentation
TEST_F (CleanTest , CleanAll)
Definition at line 28 of file clean_test.cc.
References AssertParse(), Cleaner::CleanAll(), and Cleaner::cleaned_files_count().
TEST_F (CleanTest , CleanAllDryRun)
Definition at line 58 of file clean_test.cc.
References AssertParse(), Cleaner::CleanAll(), and Cleaner::cleaned_files_count().
TEST_F (CleanTest , CleanTarget)
Definition at line 89 of file clean_test.cc.
References AssertParse(), Cleaner::cleaned_files_count(), and Cleaner::CleanTarget().
TEST_F (CleanTest , CleanTargetDryRun)
Definition at line 119 of file clean_test.cc.
References AssertParse(), Cleaner::cleaned_files_count(), and Cleaner::CleanTarget().
TEST_F (CleanTest , CleanRule)
Definition at line 150 of file clean_test.cc.
References AssertParse(), Cleaner::cleaned_files_count(), and Cleaner::CleanRule().
TEST_F (CleanTest , CleanRuleDryRun)
Definition at line 182 of file clean_test.cc.
References AssertParse(), Cleaner::cleaned_files_count(), and Cleaner::CleanRule().
TEST_F (CleanTest , CleanRuleGenerator)
Definition at line 215 of file clean_test.cc.
References AssertParse(), Cleaner::CleanAll(), and Cleaner::cleaned_files_count().
TEST_F (CleanTest , CleanDepFile)
Definition at line 237 of file clean_test.cc.
References AssertParse(), Cleaner::CleanAll(), and Cleaner::cleaned_files_count().
TEST_F (CleanTest , CleanDepFileOnCleanTarget)
Definition at line 252 of file clean_test.cc.
References AssertParse(), Cleaner::cleaned_files_count(), and Cleaner::CleanTarget().
TEST_F (CleanTest , CleanDepFileOnCleanRule)
Definition at line 267 of file clean_test.cc.
References AssertParse(), Cleaner::cleaned_files_count(), and Cleaner::CleanRule().
TEST_F (CleanTest , CleanRspFile)
Definition at line 282 of file clean_test.cc.
References AssertParse(), Cleaner::CleanAll(), and Cleaner::cleaned_files_count().
TEST_F (CleanTest , CleanRsp)
Definition at line 300 of file clean_test.cc.
References AssertParse(), Cleaner::cleaned_files_count(), Cleaner::CleanRule(), and Cleaner::CleanTarget().
TEST_F (CleanTest , CleanFailure)
Definition at line 343 of file clean_test.cc.
References AssertParse(), and Cleaner::CleanAll().
TEST_F (CleanTest , CleanPhony)
Definition at line 351 of file clean_test.cc.
References AssertParse(), Cleaner::CleanAll(), Cleaner::cleaned_files_count(), and Cleaner::CleanTarget().