Ninja: edit_distance_test.cc File Reference
edit_distance_test.cc File Reference
#include "edit_distance.h"
#include "test.h"
Functions
TEST (EditDistanceTest, TestEmpty)
TEST (EditDistanceTest, TestMaxDistance)
TEST (EditDistanceTest, TestAllowReplacements)
TEST (EditDistanceTest, TestBasics)
Function Documentation
TEST (EditDistanceTest , TestEmpty)
Definition at line 19 of file edit_distance_test.cc.
References EditDistance().
TEST (EditDistanceTest , TestMaxDistance)
Definition at line 25 of file edit_distance_test.cc.
References EditDistance().
TEST (EditDistanceTest , TestAllowReplacements)
Definition at line 34 of file edit_distance_test.cc.
References EditDistance().
TEST (EditDistanceTest , TestBasics)
Definition at line 44 of file edit_distance_test.cc.
References EditDistance().