Ninja: edit_distance.cc File Reference
edit_distance.cc File Reference
#include "edit_distance.h"
#include <algorithm>
#include <vector>
Functions
int EditDistance (const StringPiece &s1, const StringPiece &s2, bool allow_replacements, int max_edit_distance)
Function Documentation
int EditDistance (const StringPiece & s1, const StringPiece & s2, bool allow_replacements, int max_edit_distance)
Definition at line 20 of file edit_distance.cc.
References StringPiece::len_, and StringPiece::str_.
Referenced by State::SpellcheckNode(), SpellcheckStringV(), and TEST().