Ninja: edit_distance.h File Reference
edit_distance.h File Reference
#include "string_piece.h"
Functions
int EditDistance (const StringPiece &s1, const StringPiece &s2, bool allow_replacements=true, int max_edit_distance=0)
Function Documentation
int EditDistance (const StringPiece & s1, const StringPiece & s2, bool allow_replacements = true, int max_edit_distance = 0)
Definition at line 20 of file edit_distance.cc.
References StringPiece::len_, and StringPiece::str_.
Referenced by State::SpellcheckNode(), SpellcheckStringV(), and TEST().