Ninja: graph_test.cc File Reference
graph_test.cc File Reference
#include "graph.h"
#include "build.h"
#include "test.h"
Classes
struct GraphTest
Functions
TEST_F (GraphTest, MissingImplicit)
TEST_F (GraphTest, ModifiedImplicit)
TEST_F (GraphTest, FunkyMakefilePath)
TEST_F (GraphTest, ExplicitImplicit)
TEST_F (GraphTest, PathWithCurrentDirectory)
TEST_F (GraphTest, RootNodes)
TEST_F (GraphTest, VarInOutPathEscaping)
TEST_F (GraphTest, DepfileWithCanonicalizablePath)
TEST_F (GraphTest, DepfileRemoved)
TEST_F (GraphTest, RuleVariablesInScope)
TEST_F (GraphTest, DepfileOverride)
TEST_F (GraphTest, DepfileOverrideParent)
TEST_F (GraphTest, NestedPhonyPrintsDone)
Function Documentation
TEST_F (GraphTest , MissingImplicit)
Definition at line 27 of file graph_test.cc.
References AssertParse().
TEST_F (GraphTest , ModifiedImplicit)
Definition at line 44 of file graph_test.cc.
References AssertParse().
TEST_F (GraphTest , FunkyMakefilePath)
Definition at line 61 of file graph_test.cc.
References AssertParse().
TEST_F (GraphTest , ExplicitImplicit)
Definition at line 83 of file graph_test.cc.
References AssertParse().
TEST_F (GraphTest , PathWithCurrentDirectory)
Definition at line 108 of file graph_test.cc.
References AssertParse().
TEST_F (GraphTest , RootNodes)
Definition at line 126 of file graph_test.cc.
References AssertParse().
TEST_F (GraphTest , VarInOutPathEscaping)
Definition at line 142 of file graph_test.cc.
References AssertParse(), and Edge::EvaluateCommand().
TEST_F (GraphTest , DepfileWithCanonicalizablePath)
Definition at line 157 of file graph_test.cc.
References AssertParse().
TEST_F (GraphTest , DepfileRemoved)
Definition at line 176 of file graph_test.cc.
References AssertParse().
TEST_F (GraphTest , RuleVariablesInScope)
Definition at line 202 of file graph_test.cc.
References AssertParse(), and Edge::EvaluateCommand().
TEST_F (GraphTest , DepfileOverride)
Definition at line 213 of file graph_test.cc.
References AssertParse(), and Edge::GetBinding().
TEST_F (GraphTest , DepfileOverrideParent)
Definition at line 225 of file graph_test.cc.
References AssertParse(), and Edge::GetBinding().
TEST_F (GraphTest , NestedPhonyPrintsDone)
Definition at line 237 of file graph_test.cc.
References Plan::AddTarget(), AssertParse(), Plan::command_edge_count(), and Plan::more_to_do().