Ninja: hash_collision_bench.cc File Reference
hash_collision_bench.cc File Reference
#include "build_log.h"
#include <algorithm>
#include <time.h>
Functions
int main ()
int random (int low, int high)
void RandomCommand (char **s)
Function Documentation
int main ()
Definition at line 33 of file hash_collision_bench.cc.
References BuildLog::LogEntry::HashCommand(), and RandomCommand().
int random (int low, int high)
Definition at line 22 of file hash_collision_bench.cc.
Referenced by RandomCommand().
void RandomCommand (char ** s)
Definition at line 26 of file hash_collision_bench.cc.
References random().
Referenced by main().