Ninja: includes_normalize_test.cc File Reference
includes_normalize_test.cc File Reference
#include "includes_normalize.h"
#include <gtest/gtest.h>
#include "test.h"
#include "util.h"
Functions
TEST (IncludesNormalize, Simple)
TEST (IncludesNormalize, WithRelative)
TEST (IncludesNormalize, Case)
TEST (IncludesNormalize, Join)
TEST (IncludesNormalize, Split)
TEST (IncludesNormalize, ToLower)
TEST (IncludesNormalize, DifferentDrive)
Function Documentation
TEST (IncludesNormalize , Simple)
Definition at line 22 of file includes_normalize_test.cc.
References IncludesNormalize::Normalize().
TEST (IncludesNormalize , WithRelative)
Definition at line 40 of file includes_normalize_test.cc.
References IncludesNormalize::AbsPath(), IncludesNormalize::Normalize(), and IncludesNormalize::ToLower().
TEST (IncludesNormalize , Case)
Definition at line 53 of file includes_normalize_test.cc.
References IncludesNormalize::Normalize().
TEST (IncludesNormalize , Join)
Definition at line 62 of file includes_normalize_test.cc.
References IncludesNormalize::Join().
TEST (IncludesNormalize , Split)
Definition at line 72 of file includes_normalize_test.cc.
References IncludesNormalize::Join(), and IncludesNormalize::Split().
TEST (IncludesNormalize , ToLower)
Definition at line 82 of file includes_normalize_test.cc.
References IncludesNormalize::ToLower().
TEST (IncludesNormalize , DifferentDrive)
Definition at line 90 of file includes_normalize_test.cc.
References IncludesNormalize::Normalize().