Ninja: lexer_test.cc File Reference
lexer_test.cc File Reference
#include "lexer.h"
#include <gtest/gtest.h>
#include "eval_env.h"
Functions
TEST (Lexer, ReadVarValue)
TEST (Lexer, ReadEvalStringEscapes)
TEST (Lexer, ReadIdent)
TEST (Lexer, ReadIdentCurlies)
TEST (Lexer, Error)
TEST (Lexer, CommentEOF)
TEST (Lexer, Tabs)
Function Documentation
TEST (Lexer , ReadVarValue)
Definition at line 21 of file lexer_test.cc.
References Lexer::ReadVarValue(), and EvalString::Serialize().
TEST (Lexer , ReadEvalStringEscapes)
Definition at line 31 of file lexer_test.cc.
References Lexer::ReadVarValue(), and EvalString::Serialize().
TEST (Lexer , ReadIdent)
Definition at line 41 of file lexer_test.cc.
References Lexer::ReadIdent().
TEST (Lexer , ReadIdentCurlies)
Definition at line 54 of file lexer_test.cc.
References Lexer::ReadIdent(), Lexer::ReadVarValue(), and EvalString::Serialize().
TEST (Lexer , Error)
Definition at line 70 of file lexer_test.cc.
References Lexer::ReadVarValue().
TEST (Lexer , CommentEOF)
Definition at line 81 of file lexer_test.cc.
References Lexer::ERROR, and Lexer::ReadToken().
TEST (Lexer , Tabs)
Definition at line 89 of file lexer_test.cc.
References Lexer::DescribeLastError(), Lexer::ERROR, Lexer::INDENT, and Lexer::ReadToken().