Ninja: manifest_parser_test.cc File Reference
manifest_parser_test.cc File Reference
#include "manifest_parser.h"
#include <map>
#include <vector>
#include <gtest/gtest.h>
#include "graph.h"
#include "state.h"
Classes
struct ParserTest
Functions
TEST_F (ParserTest, Empty)
TEST_F (ParserTest, Rules)
TEST_F (ParserTest, RuleAttributes)
TEST_F (ParserTest, IgnoreIndentedComments)
TEST_F (ParserTest, IgnoreIndentedBlankLines)
TEST_F (ParserTest, ResponseFiles)
TEST_F (ParserTest, InNewline)
TEST_F (ParserTest, Variables)
TEST_F (ParserTest, VariableScope)
TEST_F (ParserTest, Continuation)
TEST_F (ParserTest, Backslash)
TEST_F (ParserTest, Comment)
TEST_F (ParserTest, Dollars)
TEST_F (ParserTest, EscapeSpaces)
TEST_F (ParserTest, CanonicalizeFile)
TEST_F (ParserTest, PathVariables)
TEST_F (ParserTest, CanonicalizePaths)
TEST_F (ParserTest, ReservedWords)
TEST_F (ParserTest, Errors)
TEST_F (ParserTest, MissingInput)
TEST_F (ParserTest, MultipleOutputs)
TEST_F (ParserTest, MultipleOutputsWithDeps)
TEST_F (ParserTest, SubNinja)
TEST_F (ParserTest, MissingSubNinja)
TEST_F (ParserTest, DuplicateRuleInDifferentSubninjas)
TEST_F (ParserTest, Include)
TEST_F (ParserTest, BrokenInclude)
TEST_F (ParserTest, Implicit)
TEST_F (ParserTest, OrderOnly)
TEST_F (ParserTest, DefaultDefault)
TEST_F (ParserTest, DefaultStatements)
TEST_F (ParserTest, UTF8)
TEST_F (ParserTest, CRLF)
Function Documentation
TEST_F (ParserTest , Empty)
Definition at line 50 of file manifest_parser_test.cc.
References AssertParse().
TEST_F (ParserTest , Rules)
Definition at line 54 of file manifest_parser_test.cc.
References AssertParse().
TEST_F (ParserTest , RuleAttributes)
Definition at line 71 of file manifest_parser_test.cc.
References AssertParse().
TEST_F (ParserTest , IgnoreIndentedComments)
Definition at line 86 of file manifest_parser_test.cc.
References AssertParse().
TEST_F (ParserTest , IgnoreIndentedBlankLines)
Definition at line 105 of file manifest_parser_test.cc.
References AssertParse().
TEST_F (ParserTest , ResponseFiles)
Definition at line 120 of file manifest_parser_test.cc.
References AssertParse().
TEST_F (ParserTest , InNewline)
Definition at line 139 of file manifest_parser_test.cc.
References AssertParse().
TEST_F (ParserTest , Variables)
Definition at line 157 of file manifest_parser_test.cc.
References AssertParse().
TEST_F (ParserTest , VariableScope)
Definition at line 182 of file manifest_parser_test.cc.
References AssertParse().
TEST_F (ParserTest , Continuation)
Definition at line 199 of file manifest_parser_test.cc.
References AssertParse().
TEST_F (ParserTest , Backslash)
Definition at line 214 of file manifest_parser_test.cc.
References AssertParse().
TEST_F (ParserTest , Comment)
Definition at line 223 of file manifest_parser_test.cc.
References AssertParse().
TEST_F (ParserTest , Dollars)
Definition at line 230 of file manifest_parser_test.cc.
References AssertParse().
TEST_F (ParserTest , EscapeSpaces)
Definition at line 246 of file manifest_parser_test.cc.
References AssertParse().
TEST_F (ParserTest , CanonicalizeFile)
Definition at line 259 of file manifest_parser_test.cc.
References AssertParse().
TEST_F (ParserTest , PathVariables)
Definition at line 273 of file manifest_parser_test.cc.
References AssertParse().
TEST_F (ParserTest , CanonicalizePaths)
Definition at line 284 of file manifest_parser_test.cc.
References AssertParse().
TEST_F (ParserTest , ReservedWords)
Definition at line 296 of file manifest_parser_test.cc.
References AssertParse().
TEST_F (ParserTest , Errors)
Definition at line 304 of file manifest_parser_test.cc.
References ManifestParser::ParseTest().
TEST_F (ParserTest , MissingInput)
Definition at line 705 of file manifest_parser_test.cc.
References ManifestParser::Load().
TEST_F (ParserTest , MultipleOutputs)
Definition at line 713 of file manifest_parser_test.cc.
References ManifestParser::ParseTest().
TEST_F (ParserTest , MultipleOutputsWithDeps)
Definition at line 723 of file manifest_parser_test.cc.
References ManifestParser::ParseTest().
TEST_F (ParserTest , SubNinja)
Definition at line 734 of file manifest_parser_test.cc.
References AssertParse().
TEST_F (ParserTest , MissingSubNinja)
Definition at line 759 of file manifest_parser_test.cc.
References ManifestParser::ParseTest().
TEST_F (ParserTest , DuplicateRuleInDifferentSubninjas)
Definition at line 769 of file manifest_parser_test.cc.
References ManifestParser::ParseTest().
TEST_F (ParserTest , Include)
Definition at line 784 of file manifest_parser_test.cc.
References AssertParse().
TEST_F (ParserTest , BrokenInclude)
Definition at line 795 of file manifest_parser_test.cc.
References ManifestParser::ParseTest().
TEST_F (ParserTest , Implicit)
Definition at line 806 of file manifest_parser_test.cc.
References AssertParse(), and Edge::is_implicit().
TEST_F (ParserTest , OrderOnly)
Definition at line 816 of file manifest_parser_test.cc.
References AssertParse(), and Edge::is_order_only().
TEST_F (ParserTest , DefaultDefault)
Definition at line 825 of file manifest_parser_test.cc.
References AssertParse().
TEST_F (ParserTest , DefaultStatements)
Definition at line 838 of file manifest_parser_test.cc.
References AssertParse().
TEST_F (ParserTest , UTF8)
Definition at line 858 of file manifest_parser_test.cc.
References AssertParse().
TEST_F (ParserTest , CRLF)
Definition at line 867 of file manifest_parser_test.cc.
References ManifestParser::ParseTest().