Ninja: manifest_parser_perftest.cc File Reference
manifest_parser_perftest.cc File Reference
#include <numeric>
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <getopt.h>
#include <unistd.h>
#include "disk_interface.h"
#include "graph.h"
#include "manifest_parser.h"
#include "metrics.h"
#include "state.h"
#include "util.h"
Classes
struct RealFileReader
Functions
int LoadManifests (bool measure_command_evaluation)
int main (int argc, char *argv[])
bool WriteFakeManifests (const string &dir)
Function Documentation
int LoadManifests (bool measure_command_evaluation)
Definition at line 56 of file manifest_parser_perftest.cc.
References State::edges_, and ManifestParser::Load().
Referenced by main().
int main (int argc, char * argv[])
Definition at line 75 of file manifest_parser_perftest.cc.
References Fatal(), getopt(), GetTimeMillis(), LoadManifests(), and WriteFakeManifests().
bool WriteFakeManifests (const string & dir)
Definition at line 45 of file manifest_parser_perftest.cc.
References RealDiskInterface::Stat().
Referenced by main().