Ninja: metrics.cc File Reference
metrics.cc File Reference
#include "metrics.h"
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <sys/time.h>
#include "util.h"
Functions
int64_t GetTimeMillis ()
Get the current time as relative to some epoch.
Variables
Metrics * g_metrics = NULL
Function Documentation
int64_t GetTimeMillis ()
Get the current time as relative to some epoch.
Epoch varies between platforms; only useful for measuring elapsed time.
Definition at line 122 of file metrics.cc.
Referenced by BuildStatus::BuildEdgeFinished(), BuildStatus::BuildEdgeStarted(), and main().
Variable Documentation
Metrics* g_metrics = NULL
Definition at line 29 of file metrics.cc.