Ninja: minidump-win32.cc File Reference
minidump-win32.cc File Reference
#include <windows.h>
#include <DbgHelp.h>
#include "util.h"
Typedefs
typedef IN DWORD
typedef IN IN HANDLE
typedef IN IN IN MINIDUMP_TYPE
typedef IN IN IN IN CONST
OPTIONAL IN CONST OPTIONAL IN
CONST
PMINIDUMP_CALLBACK_INFORMATION OPTIONAL
typedef IN IN IN IN CONST PMINIDUMP_EXCEPTION_INFORMATION
typedef IN IN IN IN CONST
OPTIONAL IN CONST PMINIDUMP_USER_STREAM_INFORMATION
Functions
typedef BOOL (WINAPI *MiniDumpWriteDumpFunc)(IN HANDLE
void CreateWin32MiniDump (_EXCEPTION_POINTERS *pep)
Creates a windows minidump in temp folder.
Typedef Documentation
typedef IN DWORD
Definition at line 25 of file minidump-win32.cc.
typedef IN IN HANDLE
Definition at line 25 of file minidump-win32.cc.
typedef IN IN IN MINIDUMP_TYPE
Definition at line 25 of file minidump-win32.cc.
typedef IN IN IN IN CONST OPTIONAL IN CONST OPTIONAL IN CONST PMINIDUMP_CALLBACK_INFORMATION OPTIONAL
Definition at line 25 of file minidump-win32.cc.
typedef IN IN IN IN CONST PMINIDUMP_EXCEPTION_INFORMATION
Definition at line 25 of file minidump-win32.cc.
typedef IN IN IN IN CONST OPTIONAL IN CONST PMINIDUMP_USER_STREAM_INFORMATION
Definition at line 25 of file minidump-win32.cc.
Function Documentation
typedef BOOL (WINAPI * MiniDumpWriteDumpFunc)
Referenced by CreateWin32MiniDump().
void CreateWin32MiniDump (_EXCEPTION_POINTERS * pep)
Creates a windows minidump in temp folder.
Definition at line 34 of file minidump-win32.cc.
References BOOL(), Error(), and Warning().