Ninja: msvc_helper_test.cc File Reference
msvc_helper_test.cc File Reference
#include "msvc_helper.h"
#include <gtest/gtest.h>
#include "test.h"
#include "util.h"
Functions
TEST (CLParserTest, ShowIncludes)
TEST (CLParserTest, FilterInputFilename)
TEST (CLParserTest, ParseSimple)
TEST (CLParserTest, ParseFilenameFilter)
TEST (CLParserTest, ParseSystemInclude)
TEST (CLParserTest, DuplicatedHeader)
TEST (CLParserTest, DuplicatedHeaderPathConverted)
TEST (CLParserTest, SpacesInFilename)
TEST (MSVCHelperTest, EnvBlock)
TEST (MSVCHelperTest, NoReadOfStderr)
Function Documentation
TEST (CLParserTest , ShowIncludes)
Definition at line 22 of file msvc_helper_test.cc.
References CLParser::FilterShowIncludes().
TEST (CLParserTest , FilterInputFilename)
Definition at line 38 of file msvc_helper_test.cc.
References CLParser::FilterInputFilename().
TEST (CLParserTest , ParseSimple)
Definition at line 49 of file msvc_helper_test.cc.
References CLParser::includes_, and CLParser::Parse().
TEST (CLParserTest , ParseFilenameFilter)
Definition at line 62 of file msvc_helper_test.cc.
References CLParser::Parse().
TEST (CLParserTest , ParseSystemInclude)
Definition at line 71 of file msvc_helper_test.cc.
References CLParser::includes_, and CLParser::Parse().
TEST (CLParserTest , DuplicatedHeader)
Definition at line 85 of file msvc_helper_test.cc.
References CLParser::includes_, and CLParser::Parse().
TEST (CLParserTest , DuplicatedHeaderPathConverted)
Definition at line 97 of file msvc_helper_test.cc.
References CLParser::includes_, and CLParser::Parse().
TEST (CLParserTest , SpacesInFilename)
Definition at line 109 of file msvc_helper_test.cc.
References EscapeForDepfile().
TEST (MSVCHelperTest , EnvBlock)
Definition at line 114 of file msvc_helper_test.cc.
References CLWrapper::Run(), and CLWrapper::SetEnvBlock().
TEST (MSVCHelperTest , NoReadOfStderr)
Definition at line 123 of file msvc_helper_test.cc.
References CLWrapper::Run().