Ninja: parser_perftest.cc File Reference
parser_perftest.cc File Reference
#include <stdio.h>
#include <stdlib.h>
#include "depfile_parser.h"
#include "util.h"
#include "metrics.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 22 of file parser_perftest.cc.
References GetTimeMillis(), DepfileParser::Parse(), and ReadFile().