Ninja: CLWrapper Struct Reference
CLWrapper Struct Reference
Wraps a synchronous execution of a CL subprocess.
#include <msvc_helper.h>
Public Member Functions
CLWrapper ()
int Run (const string &command, string *output)
Start a process and gather its raw output.
void SetEnvBlock (void *env_block)
Set the environment block (as suitable for CreateProcess) to be used by Run().
Public Attributes
void * env_block_
Detailed Description
Wraps a synchronous execution of a CL subprocess.
Definition at line 51 of file msvc_helper.h.
Constructor & Destructor Documentation
CLWrapper::CLWrapper () [inline]
Definition at line 52 of file msvc_helper.h.
Member Function Documentation
int CLWrapper::Run (const string & command, string * output)
Start a process and gather its raw output.
Returns its exit code. Crashes (calls Fatal()) on error.
Definition at line 120 of file msvc_helper-win32.cc.
References env_block_, Fatal(), and ReadFile().
Referenced by MSVCHelperMain(), and TEST().
void CLWrapper::SetEnvBlock (void * env_block) [inline]
Set the environment block (as suitable for CreateProcess) to be used by Run().
Definition at line 56 of file msvc_helper.h.
Referenced by MSVCHelperMain(), and TEST().
Member Data Documentation
void* CLWrapper::env_block_
Definition at line 62 of file msvc_helper.h.
Referenced by Run().
The documentation for this struct was generated from the following files:
msvc_helper.h
msvc_helper-win32.cc