Ninja: PlanTest Struct Reference
PlanTest Struct Reference
Fixture for tests involving Plan.
Public Member Functions
void AddCatRule (State *state)
Add a "cat" rule to state.
void FindWorkSorted (deque< Edge * > *ret, int count)
Because FindWork does not return Edges in any sort of predictable order,.
Node * GetNode (const string &path)
Short way to get a Node by its path from state_.
Public Attributes
Plan plan_
State state_
Detailed Description
Fixture for tests involving Plan.
Definition at line 25 of file build_test.cc.
Member Function Documentation
void StateTestWithBuiltinRules::AddCatRule (State * state) [inherited]
Add a "cat" rule to state.
Used by some tests; it's otherwise done by the ctor to state_.
Definition at line 80 of file test.cc.
References AssertParse().
Referenced by BuildTest::RebuildTarget(), and StateTestWithBuiltinRules::StateTestWithBuiltinRules().
void PlanTest::FindWorkSorted (deque< Edge * > * ret, int count) [inline]
Because FindWork does not return Edges in any sort of predictable order,.
Definition at line 31 of file build_test.cc.
References Plan::FindWork(), Plan::more_to_do(), Edge::outputs_, and plan_.
Node * StateTestWithBuiltinRules::GetNode (const string & path) [inherited]
Short way to get a Node by its path from state_.
Definition at line 86 of file test.cc.
References State::GetNode(), and StateTestWithBuiltinRules::state_.
Referenced by BuildTest::Dirty().
Member Data Documentation
Plan PlanTest::plan_
Definition at line 26 of file build_test.cc.
Referenced by FindWorkSorted().
State StateTestWithBuiltinRules::state_ [inherited]
Definition at line 40 of file test.h.
Referenced by StateTestWithBuiltinRules::GetNode(), BuildTest::SetUp(), and StateTestWithBuiltinRules::StateTestWithBuiltinRules().
The documentation for this struct was generated from the following file:
build_test.cc