Ninja: BuildDryRun Struct Reference
BuildDryRun Struct Reference
Public Member Functions
void AddCatRule (State *state)
Add a "cat" rule to state.
BuildDryRun ()
void Dirty (const string &path)
Node * GetNode (const string &path)
Short way to get a Node by its path from state_.
BuildConfig MakeConfig ()
virtual void SetUp ()
Public Attributes
BuildLog build_log_
Builder builder_
FakeCommandRunner command_runner_
BuildConfig config_
VirtualFileSystem fs_
State state_
BuildStatus status_
Detailed Description
Definition at line 1151 of file build_test.cc.
Constructor & Destructor Documentation
BuildDryRun::BuildDryRun () [inline]
Definition at line 1152 of file build_test.cc.
References BuildTest::config_, and BuildConfig::dry_run.
Member Function Documentation
void StateTestWithBuiltinRules::AddCatRule (State * state) [inherited]
Add a "cat" rule to state.
Used by some tests; it's otherwise done by the ctor to state_.
Definition at line 80 of file test.cc.
References AssertParse().
Referenced by StateTestWithBuiltinRules::StateTestWithBuiltinRules().
void BuildTest::Dirty (const string & path) [inherited]
Definition at line 517 of file build_test.cc.
References StateTestWithBuiltinRules::GetNode(), Node::in_edge(), Node::MarkDirty(), and Node::MarkMissing().
Node * StateTestWithBuiltinRules::GetNode (const string & path) [inherited]
Short way to get a Node by its path from state_.
Definition at line 86 of file test.cc.
References State::GetNode(), and StateTestWithBuiltinRules::state_.
Referenced by BuildTest::Dirty().
BuildConfig BuildTest::MakeConfig () [inline, inherited]
Definition at line 441 of file build_test.cc.
References BuildConfig::QUIET, and BuildConfig::verbosity.
virtual void BuildTest::SetUp () [inline, virtual, inherited]
Reimplemented in BuildWithDepsLogTest.
Definition at line 421 of file build_test.cc.
References AssertParse(), BuildTest::builder_, Builder::command_runner_, BuildTest::command_runner_, VirtualFileSystem::Create(), BuildTest::fs_, and StateTestWithBuiltinRules::state_.
Member Data Documentation
BuildLog BuildWithLogTest::build_log_ [inherited]
Definition at line 965 of file build_test.cc.
Referenced by BuildWithLogTest::BuildWithLogTest().
Builder BuildTest::builder_ [inherited]
Reimplemented in BuildWithDepsLogTest.
Definition at line 450 of file build_test.cc.
Referenced by BuildWithLogTest::BuildWithLogTest(), BuildTest::SetUp(), and BuildTest::~BuildTest().
FakeCommandRunner BuildTest::command_runner_ [inherited]
Definition at line 448 of file build_test.cc.
Referenced by BuildTest::SetUp().
BuildConfig BuildTest::config_ [inherited]
Definition at line 447 of file build_test.cc.
Referenced by BuildDryRun().
VirtualFileSystem BuildTest::fs_ [inherited]
Definition at line 449 of file build_test.cc.
Referenced by BuildTest::SetUp().
State StateTestWithBuiltinRules::state_ [inherited]
Definition at line 40 of file test.h.
Referenced by StateTestWithBuiltinRules::GetNode(), BuildTest::SetUp(), and StateTestWithBuiltinRules::StateTestWithBuiltinRules().
BuildStatus BuildTest::status_ [inherited]
Definition at line 452 of file build_test.cc.
The documentation for this struct was generated from the following file:
build_test.cc