Ninja: StateTestWithBuiltinRules Struct Reference
StateTestWithBuiltinRules Struct Reference
A base test fixture that includes a State object with a builtin "cat" rule.
#include <test.h>
Public Member Functions
void AddCatRule (State *state)
Add a "cat" rule to state.
Node * GetNode (const string &path)
Short way to get a Node by its path from state_.
StateTestWithBuiltinRules ()
Public Attributes
State state_
Detailed Description
A base test fixture that includes a State object with a builtin "cat" rule.
Definition at line 30 of file test.h.
Constructor & Destructor Documentation
StateTestWithBuiltinRules::StateTestWithBuiltinRules ()
Definition at line 76 of file test.cc.
References AddCatRule(), and state_.
Member Function Documentation
void StateTestWithBuiltinRules::AddCatRule (State * state)
Add a "cat" rule to state.
Used by some tests; it's otherwise done by the ctor to state_.
Definition at line 80 of file test.cc.
References AssertParse().
Referenced by BuildTest::RebuildTarget(), and StateTestWithBuiltinRules().
Node * StateTestWithBuiltinRules::GetNode (const string & path)
Short way to get a Node by its path from state_.
Definition at line 86 of file test.cc.
References State::GetNode(), and state_.
Referenced by BuildTest::Dirty(), and PlanTest::TestPoolWithDepthOne().
Member Data Documentation
State StateTestWithBuiltinRules::state_
Definition at line 40 of file test.h.
Referenced by GetNode(), BuildTest::SetUp(), StateTestWithBuiltinRules(), and PlanTest::TestPoolWithDepthOne().
The documentation for this struct was generated from the following files:
test.h
test.cc