Ninja: BuildStatus::RateInfo Struct Reference
BuildStatus::RateInfo Struct Reference
Public Member Functions
double Elapsed () const
double rate ()
RateInfo ()
void Restart ()
void UpdateRate (int edges)
Private Attributes
double rate_
Stopwatch stopwatch_
Detailed Description
Definition at line 235 of file build.h.
Constructor & Destructor Documentation
BuildStatus::RateInfo::RateInfo () [inline]
Definition at line 236 of file build.h.
Member Function Documentation
double BuildStatus::RateInfo::Elapsed () const [inline]
Definition at line 239 of file build.h.
References Stopwatch::Elapsed(), and stopwatch_.
Referenced by BuildStatus::FormatProgressStatus().
double BuildStatus::RateInfo::rate () [inline]
Definition at line 240 of file build.h.
References rate_.
Referenced by BuildStatus::FormatProgressStatus().
void BuildStatus::RateInfo::Restart () [inline]
Definition at line 238 of file build.h.
References Stopwatch::Restart(), and stopwatch_.
Referenced by BuildStatus::PrintStatus().
void BuildStatus::RateInfo::UpdateRate (int edges) [inline]
Definition at line 242 of file build.h.
References Stopwatch::Elapsed(), rate_, and stopwatch_.
Referenced by BuildStatus::FormatProgressStatus().
Member Data Documentation
double BuildStatus::RateInfo::rate_ [private]
Definition at line 248 of file build.h.
Referenced by rate(), and UpdateRate().
Stopwatch BuildStatus::RateInfo::stopwatch_ [private]
Definition at line 249 of file build.h.
Referenced by Elapsed(), Restart(), and UpdateRate().
The documentation for this struct was generated from the following file:
build.h