Ninja: BuildWithDepsLogTest Struct Reference
BuildWithDepsLogTest Struct Reference
Tests of builds involving deps logs necessarily must span multiple builds.
Public Member Functions
void AddCatRule (State *state)
Add a "cat" rule to state.
BuildWithDepsLogTest ()
void Dirty (const string &path)
Node * GetNode (const string &path)
Short way to get a Node by its path from state_.
BuildConfig MakeConfig ()
void RebuildTarget (const string &target, const char *manifest, const char *log_path=NULL, const char *deps_path=NULL)
Rebuild target in the 'working tree' (fs_).
virtual void SetUp ()
virtual void TearDown ()
Public Attributes
void * builder_
Shadow parent class builder_ so we don't accidentally use it.
FakeCommandRunner command_runner_
BuildConfig config_
VirtualFileSystem fs_
State state_
BuildStatus status_
ScopedTempDir temp_dir_
Detailed Description
Tests of builds involving deps logs necessarily must span multiple builds.
We reuse methods on BuildTest but not the builder_ it sets up, because we want pristine objects for each build.
Definition at line 1503 of file build_test.cc.
Constructor & Destructor Documentation
BuildWithDepsLogTest::BuildWithDepsLogTest () [inline]
Definition at line 1504 of file build_test.cc.
Member Function Documentation
void StateTestWithBuiltinRules::AddCatRule (State * state) [inherited]
Add a "cat" rule to state.
Used by some tests; it's otherwise done by the ctor to state_.
Definition at line 80 of file test.cc.
References AssertParse().
Referenced by BuildTest::RebuildTarget(), and StateTestWithBuiltinRules::StateTestWithBuiltinRules().
void BuildTest::Dirty (const string & path) [inherited]
Definition at line 559 of file build_test.cc.
References StateTestWithBuiltinRules::GetNode(), Node::in_edge(), Node::MarkDirty(), and Node::MarkMissing().
Node * StateTestWithBuiltinRules::GetNode (const string & path) [inherited]
Short way to get a Node by its path from state_.
Definition at line 86 of file test.cc.
References State::GetNode(), and StateTestWithBuiltinRules::state_.
Referenced by BuildTest::Dirty().
BuildConfig BuildTest::MakeConfig () [inline, inherited]
Definition at line 448 of file build_test.cc.
References BuildConfig::QUIET, and BuildConfig::verbosity.
void BuildTest::RebuildTarget (const string & target, const char * manifest, const char * log_path = NULL, const char * deps_path = NULL) [inherited]
Rebuild target in the 'working tree' (fs_).
State of command_runner_ and logs contents (if specified) ARE MODIFIED. Handy to check for NOOP builds, and higher-level rebuild tests.
Definition at line 462 of file build_test.cc.
References StateTestWithBuiltinRules::AddCatRule(), Builder::AddTarget(), Builder::AlreadyUpToDate(), AssertParse(), Builder::Build(), Builder::command_runner_, BuildTest::command_runner_, FakeCommandRunner::commands_ran_, BuildTest::config_, BuildTest::fs_, BuildLog::Load(), DepsLog::Load(), BuildLog::OpenForWrite(), and DepsLog::OpenForWrite().
virtual void BuildWithDepsLogTest::SetUp () [inline, virtual]
Reimplemented from BuildTest.
Definition at line 1506 of file build_test.cc.
References ScopedTempDir::CreateAndEnter(), and temp_dir_.
virtual void BuildWithDepsLogTest::TearDown () [inline, virtual]
Definition at line 1512 of file build_test.cc.
References ScopedTempDir::Cleanup(), and temp_dir_.
Member Data Documentation
void* BuildWithDepsLogTest::builder_
Shadow parent class builder_ so we don't accidentally use it.
Reimplemented from BuildTest.
Definition at line 1519 of file build_test.cc.
FakeCommandRunner BuildTest::command_runner_ [inherited]
Definition at line 455 of file build_test.cc.
Referenced by BuildTest::RebuildTarget(), and BuildTest::SetUp().
BuildConfig BuildTest::config_ [inherited]
Definition at line 454 of file build_test.cc.
Referenced by BuildDryRun::BuildDryRun(), and BuildTest::RebuildTarget().
VirtualFileSystem BuildTest::fs_ [inherited]
Definition at line 456 of file build_test.cc.
Referenced by BuildTest::RebuildTarget(), and BuildTest::SetUp().
State StateTestWithBuiltinRules::state_ [inherited]
Definition at line 40 of file test.h.
Referenced by StateTestWithBuiltinRules::GetNode(), BuildTest::SetUp(), and StateTestWithBuiltinRules::StateTestWithBuiltinRules().
BuildStatus BuildTest::status_ [inherited]
Definition at line 459 of file build_test.cc.
ScopedTempDir BuildWithDepsLogTest::temp_dir_
Definition at line 1516 of file build_test.cc.
Referenced by SetUp(), and TearDown().
The documentation for this struct was generated from the following file:
build_test.cc