Ninja: BuildStatus Struct Reference
BuildStatus Struct Reference
Tracks the status of a build: completion fraction, printing updates.
#include <build.h>
Classes
struct RateInfo
struct SlidingRateInfo
Public Member Functions
void BuildEdgeFinished (Edge *edge, bool success, const string &output, int *start_time, int *end_time)
void BuildEdgeStarted (Edge *edge)
void BuildFinished ()
BuildStatus (const BuildConfig &config)
string FormatProgressStatus (const char *progress_status_format) const
Format the progress status string by replacing the placeholders.
void PlanHasTotalEdges (int total)
Private Types
typedef map< Edge *, int > RunningEdgeMap
Map of running edge to time the edge started running.
Private Member Functions
void PrintStatus (Edge *edge)
template<size_t S>
void snprinfRate (double rate, char(&buf)[S], const char *format) const
Private Attributes
const BuildConfig & config_
SlidingRateInfo current_rate_
int finished_edges_
RateInfo overall_rate_
LinePrinter printer_
Prints progress output.
const char * progress_status_format_
The custom progress status format to use.
RunningEdgeMap running_edges_
int64_t start_time_millis_
Time the build started.
int started_edges_
int total_edges_
Detailed Description
Tracks the status of a build: completion fraction, printing updates.
Definition at line 195 of file build.h.
Member Typedef Documentation
typedef map<Edge*, int> BuildStatus::RunningEdgeMap [private]
Map of running edge to time the edge started running.
Definition at line 220 of file build.h.
Constructor & Destructor Documentation
BuildStatus::BuildStatus (const BuildConfig & config) [explicit]
Definition at line 74 of file build.cc.
References config_, BuildConfig::NORMAL, printer_, progress_status_format_, LinePrinter::set_smart_terminal(), and BuildConfig::verbosity.
Member Function Documentation
void BuildStatus::BuildEdgeFinished (Edge * edge, bool success, const string & output, int * start_time, int * end_time)
Definition at line 102 of file build.cc.
References config_, Edge::EvaluateCommand(), finished_edges_, GetTimeMillis(), LinePrinter::is_smart_terminal(), printer_, LinePrinter::PrintOnNewLine(), PrintStatus(), BuildConfig::QUIET, running_edges_, start_time_millis_, StripAnsiEscapeCodes(), and BuildConfig::verbosity.
Referenced by Builder::FinishCommand().
void BuildStatus::BuildEdgeStarted (Edge * edge)
Definition at line 94 of file build.cc.
References GetTimeMillis(), PrintStatus(), running_edges_, start_time_millis_, and started_edges_.
Referenced by Builder::StartEdge().
void BuildStatus::BuildFinished ()
Definition at line 147 of file build.cc.
References printer_, and LinePrinter::PrintOnNewLine().
Referenced by Builder::Build().
string BuildStatus::FormatProgressStatus (const char * progress_status_format) const
Format the progress status string by replacing the placeholders.
See the user manual for more information about the available placeholders.
Parameters:
progress_status_format The format of the progress status.
Definition at line 151 of file build.cc.
References current_rate_, BuildStatus::RateInfo::Elapsed(), Fatal(), finished_edges_, overall_rate_, BuildStatus::RateInfo::rate(), BuildStatus::SlidingRateInfo::rate(), snprinfRate(), started_edges_, total_edges_, BuildStatus::RateInfo::UpdateRate(), and BuildStatus::SlidingRateInfo::UpdateRate().
Referenced by PrintStatus().
void BuildStatus::PlanHasTotalEdges (int total)
Definition at line 90 of file build.cc.
References total_edges_.
Referenced by Builder::Build(), and Builder::FinishCommand().
void BuildStatus::PrintStatus (Edge * edge) [private]
Definition at line 234 of file build.cc.
References config_, current_rate_, LinePrinter::ELIDE, finished_edges_, FormatProgressStatus(), LinePrinter::FULL, Edge::GetBinding(), overall_rate_, LinePrinter::Print(), printer_, progress_status_format_, BuildConfig::QUIET, BuildStatus::RateInfo::Restart(), BuildStatus::SlidingRateInfo::Restart(), BuildConfig::VERBOSE, and BuildConfig::verbosity.
Referenced by BuildEdgeFinished(), and BuildEdgeStarted().
template<size_t S> void BuildStatus::snprinfRate (double rate, char(&) buf[S], const char * format) const [inline, private]
Definition at line 230 of file build.h.
Referenced by FormatProgressStatus().
Member Data Documentation
const BuildConfig& BuildStatus::config_ [private]
Definition at line 212 of file build.h.
Referenced by BuildEdgeFinished(), BuildStatus(), and PrintStatus().
SlidingRateInfo BuildStatus::current_rate_ [mutable, private]
Definition at line 279 of file build.h.
Referenced by FormatProgressStatus(), and PrintStatus().
int BuildStatus::finished_edges_ [private]
Definition at line 217 of file build.h.
Referenced by BuildEdgeFinished(), FormatProgressStatus(), and PrintStatus().
RateInfo BuildStatus::overall_rate_ [mutable, private]
Definition at line 278 of file build.h.
Referenced by FormatProgressStatus(), and PrintStatus().
LinePrinter BuildStatus::printer_ [private]
Prints progress output.
Definition at line 224 of file build.h.
Referenced by BuildEdgeFinished(), BuildFinished(), BuildStatus(), and PrintStatus().
const char* BuildStatus::progress_status_format_ [private]
The custom progress status format to use.
Definition at line 227 of file build.h.
Referenced by BuildStatus(), and PrintStatus().
RunningEdgeMap BuildStatus::running_edges_ [private]
Definition at line 221 of file build.h.
Referenced by BuildEdgeFinished(), and BuildEdgeStarted().
int64_t BuildStatus::start_time_millis_ [private]
Time the build started.
Definition at line 215 of file build.h.
Referenced by BuildEdgeFinished(), and BuildEdgeStarted().
int BuildStatus::started_edges_ [private]
Definition at line 217 of file build.h.
Referenced by BuildEdgeStarted(), and FormatProgressStatus().
int BuildStatus::total_edges_ [private]
Definition at line 217 of file build.h.
Referenced by FormatProgressStatus(), and PlanHasTotalEdges().
The documentation for this struct was generated from the following files:
build.h
build.cc