Ninja: GraphViz Struct Reference
GraphViz Struct Reference
Runs the process of creating GraphViz .dot file output.
#include <graphviz.h>
Public Member Functions
void AddTarget (Node *node)
void Finish ()
void Start ()
Public Attributes
set< Edge * > visited_edges_
set< Node * > visited_nodes_
Detailed Description
Runs the process of creating GraphViz .dot file output.
Definition at line 25 of file graphviz.h.
Member Function Documentation
void GraphViz::AddTarget (Node * node)
Definition at line 21 of file graphviz.cc.
References Node::in_edge(), Edge::inputs_, Edge::is_order_only(), Rule::name(), Edge::outputs_, Node::path(), Edge::rule_, visited_edges_, and visited_nodes_.
void GraphViz::Finish ()
Definition at line 75 of file graphviz.cc.
void GraphViz::Start ()
Definition at line 68 of file graphviz.cc.
Member Data Documentation
set<Edge*> GraphViz::visited_edges_
Definition at line 31 of file graphviz.h.
Referenced by AddTarget().
set<Node*> GraphViz::visited_nodes_
Definition at line 30 of file graphviz.h.
Referenced by AddTarget().
The documentation for this struct was generated from the following files:
graphviz.h
graphviz.cc