Ninja: CleanTest Struct Reference
CleanTest Struct Reference
Public Member Functions
void AddCatRule (State *state)
Add a "cat" rule to state.
Node * GetNode (const string &path)
Short way to get a Node by its path from state_.
virtual void SetUp ()
Public Attributes
BuildConfig config_
VirtualFileSystem fs_
State state_
Detailed Description
Definition at line 20 of file clean_test.cc.
Member Function Documentation
void StateTestWithBuiltinRules::AddCatRule (State * state) [inherited]
Add a "cat" rule to state.
Used by some tests; it's otherwise done by the ctor to state_.
Definition at line 80 of file test.cc.
References AssertParse().
Referenced by BuildTest::RebuildTarget(), and StateTestWithBuiltinRules::StateTestWithBuiltinRules().
Node * StateTestWithBuiltinRules::GetNode (const string & path) [inherited]
Short way to get a Node by its path from state_.
Definition at line 86 of file test.cc.
References State::GetNode(), and StateTestWithBuiltinRules::state_.
Referenced by BuildTest::Dirty(), and PlanTest::TestPoolWithDepthOne().
virtual void CleanTest::SetUp () [inline, virtual]
Definition at line 23 of file clean_test.cc.
References config_, BuildConfig::QUIET, and BuildConfig::verbosity.
Member Data Documentation
BuildConfig CleanTest::config_
Definition at line 22 of file clean_test.cc.
Referenced by SetUp().
VirtualFileSystem CleanTest::fs_
Definition at line 21 of file clean_test.cc.
State StateTestWithBuiltinRules::state_ [inherited]
Definition at line 40 of file test.h.
Referenced by StateTestWithBuiltinRules::GetNode(), BuildTest::SetUp(), StateTestWithBuiltinRules::StateTestWithBuiltinRules(), and PlanTest::TestPoolWithDepthOne().
The documentation for this struct was generated from the following file:
clean_test.cc