Ninja: IncludesNormalize Struct Reference
IncludesNormalize Struct Reference
Utility functions for normalizing include paths on Windows.
#include <includes_normalize.h>
Static Public Member Functions
static string AbsPath (StringPiece s)
static string Join (const vector< string > &list, char sep)
static string Normalize (const string &input, const char *relative_to)
Normalize by fixing slashes style, fixing redundant .
static string Relativize (StringPiece path, const string &start)
static vector< string > Split (const string &input, char sep)
static string ToLower (const string &s)
Detailed Description
Utility functions for normalizing include paths on Windows.
TODO: this likely duplicates functionality of CanonicalizePath; refactor.
Definition at line 23 of file includes_normalize.h.
Member Function Documentation
string IncludesNormalize::AbsPath (StringPiece s) [static]
Definition at line 68 of file includes_normalize-win32.cc.
References StringPiece::AsString().
Referenced by Normalize(), Relativize(), and TEST().
string IncludesNormalize::Join (const vector< string > & list, char sep) [static]
Definition at line 43 of file includes_normalize-win32.cc.
Referenced by Relativize(), and TEST().
string IncludesNormalize::Normalize (const string & input, const char * relative_to) [static]
Normalize by fixing slashes style, fixing redundant .
. and . and makes the path relative to |relative_to|. Case is normalized to lowercase on Windows too.
Definition at line 94 of file includes_normalize-win32.cc.
References AbsPath(), StringPiece::AsString(), CanonicalizePath(), Relativize(), and Warning().
Referenced by CLParser::Parse(), and TEST().
string IncludesNormalize::Relativize (StringPiece path, const string & start) [static]
Definition at line 74 of file includes_normalize-win32.cc.
References AbsPath(), Join(), Split(), and ToLower().
Referenced by Normalize().
vector< string > IncludesNormalize::Split (const string & input, char sep) [static]
Definition at line 53 of file includes_normalize-win32.cc.
Referenced by Relativize(), and TEST().
string IncludesNormalize::ToLower (const string & s) [static]
Definition at line 62 of file includes_normalize-win32.cc.
Referenced by Relativize(), and TEST().
The documentation for this struct was generated from the following files:
includes_normalize.h
includes_normalize-win32.cc