Ninja: Builder Struct Reference
Builder Struct Reference
Builder wraps the build process: starting commands, updating status.
#include <build.h>
Public Member Functions
Node * AddTarget (const string &name, string *err)
bool AddTarget (Node *target, string *err)
Add a target to the build, scanning dependencies.
bool AlreadyUpToDate () const
Returns true if the build targets are already up to date.
bool Build (string *err)
Run the build.
Builder (State *state, const BuildConfig &config, BuildLog *build_log, DepsLog *deps_log, DiskInterface *disk_interface)
void Cleanup ()
Clean up after interrupted commands by deleting output files.
bool FinishCommand (CommandRunner::Result *result, string *err)
Update status ninja logs following a command termination.
void SetBuildLog (BuildLog *log)
Used for tests.
bool StartEdge (Edge *edge, string *err)
~Builder ()
Public Attributes
auto_ptr< CommandRunner > command_runner_
const BuildConfig & config_
Plan plan_
State * state_
BuildStatus * status_
Private Member Functions
Builder (const Builder &other)
bool ExtractDeps (CommandRunner::Result *result, const string &deps_type, const string &deps_prefix, vector< Node * > *deps_nodes, string *err)
void operator= (const Builder &other)
Private Attributes
DiskInterface * disk_interface_
DependencyScan scan_
Detailed Description
Builder wraps the build process: starting commands, updating status.
Definition at line 143 of file build.h.
Constructor & Destructor Documentation
Builder::Builder (State * state, const BuildConfig & config, BuildLog * build_log, DepsLog * deps_log, DiskInterface * disk_interface)
Definition at line 525 of file build.cc.
References status_.
Builder::~Builder ()
Definition at line 533 of file build.cc.
References Cleanup().
Builder::Builder (const Builder & other) [private]
Member Function Documentation
Node * Builder::AddTarget (const string & name, string * err)
Definition at line 565 of file build.cc.
References State::LookupNode(), and state_.
Referenced by BuildTest::RebuildTarget(), and TEST_F().
bool Builder::AddTarget (Node * target, string * err)
Add a target to the build, scanning dependencies.
Returns:
false on error.
Definition at line 576 of file build.cc.
References Plan::AddTarget(), disk_interface_, Node::in_edge(), plan_, DependencyScan::RecomputeDirty(), scan_, and Node::StatIfNecessary().
bool Builder::AlreadyUpToDate () const
Returns true if the build targets are already up to date.
Definition at line 591 of file build.cc.
References Plan::more_to_do(), and plan_.
Referenced by Build(), and BuildTest::RebuildTarget().
bool Builder::Build (string * err)
Run the build.
Returns false on error. It is an error to call this function when AlreadyUpToDate() is true.
Definition at line 595 of file build.cc.
References AlreadyUpToDate(), BuildStatus::BuildFinished(), Cleanup(), Plan::command_edge_count(), command_runner_, config_, BuildConfig::dry_run, Plan::EdgeFinished(), ExitInterrupted, BuildConfig::failures_allowed, Plan::FindWork(), FinishCommand(), Edge::is_phony(), Plan::more_to_do(), plan_, BuildStatus::PlanHasTotalEdges(), StartEdge(), CommandRunner::Result::status, status_, and CommandRunner::Result::success().
Referenced by BuildTest::RebuildTarget(), and TEST_F().
void Builder::Cleanup ()
Clean up after interrupted commands by deleting output files.
Definition at line 537 of file build.cc.
References command_runner_, disk_interface_, DiskInterface::RemoveFile(), and DiskInterface::Stat().
Referenced by Build(), and ~Builder().
bool Builder::ExtractDeps (CommandRunner::Result * result, const string & deps_type, const string & deps_prefix, vector< Node * > * deps_nodes, string * err) [private]
Definition at line 815 of file build.cc.
References CanonicalizePath(), disk_interface_, CommandRunner::Result::edge, Fatal(), State::GetNode(), Edge::GetUnescapedDepfile(), CLParser::includes_, DepfileParser::ins_, CommandRunner::Result::output, DepfileParser::Parse(), CLParser::Parse(), DiskInterface::ReadFile(), DiskInterface::RemoveFile(), and state_.
Referenced by FinishCommand().
bool Builder::FinishCommand (CommandRunner::Result * result, string * err)
Update status ninja logs following a command termination.
Returns:
false if the build can not proceed further due to a fatal error.
Definition at line 715 of file build.cc.
References DependencyScan::build_log(), BuildStatus::BuildEdgeFinished(), Plan::CleanNode(), Plan::command_edge_count(), config_, DependencyScan::deps_log(), disk_interface_, BuildConfig::dry_run, CommandRunner::Result::edge, Plan::EdgeFinished(), ExitFailure, ExtractDeps(), g_keep_rsp, Edge::GetBinding(), Edge::GetBindingBool(), Edge::GetUnescapedDepfile(), Edge::GetUnescapedRspfile(), Edge::inputs_, METRIC_RECORD, Edge::order_only_deps_, CommandRunner::Result::output, Edge::outputs_, plan_, BuildStatus::PlanHasTotalEdges(), BuildLog::RecordCommand(), DepsLog::RecordDeps(), DiskInterface::RemoveFile(), scan_, DiskInterface::Stat(), CommandRunner::Result::status, status_, and CommandRunner::Result::success().
Referenced by Build().
void Builder::operator= (const Builder & other) [private]
void Builder::SetBuildLog (BuildLog * log) [inline]
Used for tests.
Definition at line 172 of file build.h.
References scan_, and DependencyScan::set_build_log().
Referenced by BuildWithLogTest::BuildWithLogTest().
bool Builder::StartEdge (Edge * edge, string * err)
Definition at line 682 of file build.cc.
References BuildStatus::BuildEdgeStarted(), command_runner_, disk_interface_, Edge::EvaluateCommand(), Edge::GetBinding(), Edge::GetUnescapedRspfile(), Edge::is_phony(), DiskInterface::MakeDirs(), METRIC_RECORD, Edge::outputs_, status_, and DiskInterface::WriteFile().
Referenced by Build().
Member Data Documentation
auto_ptr<CommandRunner> Builder::command_runner_
Definition at line 179 of file build.h.
Referenced by Build(), Cleanup(), BuildTest::RebuildTarget(), BuildTest::SetUp(), StartEdge(), TEST_F(), and BuildTest::~BuildTest().
const BuildConfig& Builder::config_
Definition at line 177 of file build.h.
Referenced by Build(), and FinishCommand().
DiskInterface* Builder::disk_interface_ [private]
Definition at line 187 of file build.h.
Referenced by AddTarget(), Cleanup(), ExtractDeps(), FinishCommand(), and StartEdge().
Plan Builder::plan_
Definition at line 178 of file build.h.
Referenced by AddTarget(), AlreadyUpToDate(), Build(), and FinishCommand().
DependencyScan Builder::scan_ [private]
Definition at line 188 of file build.h.
Referenced by AddTarget(), FinishCommand(), and SetBuildLog().
State* Builder::state_
Definition at line 176 of file build.h.
Referenced by AddTarget(), and ExtractDeps().
BuildStatus* Builder::status_
Definition at line 180 of file build.h.
Referenced by Build(), Builder(), FinishCommand(), and StartEdge().
The documentation for this struct was generated from the following files:
build.h
build.cc