Ninja: ScopedTempDir Struct Reference
ScopedTempDir Struct Reference
#include <test.h>
Public Member Functions
void Cleanup ()
Clean up the temporary directory.
void CreateAndEnter (const string &name)
Create a temporary directory and chdir into it.
Public Attributes
string start_dir_
The temp directory containing our dir.
string temp_dir_name_
The subdirectory name for our dir, or empty if it hasn't been set up.
Detailed Description
Definition at line 85 of file test.h.
Member Function Documentation
void ScopedTempDir::Cleanup ()
Clean up the temporary directory.
Definition at line 169 of file test.cc.
References Fatal(), start_dir_, and temp_dir_name_.
Referenced by BuildWithDepsLogTest::TearDown().
void ScopedTempDir::CreateAndEnter (const string & name)
Create a temporary directory and chdir into it.
Definition at line 147 of file test.cc.
References Fatal(), start_dir_, and temp_dir_name_.
Referenced by BuildWithDepsLogTest::SetUp().
Member Data Documentation
string ScopedTempDir::start_dir_
The temp directory containing our dir.
Definition at line 93 of file test.h.
Referenced by Cleanup(), and CreateAndEnter().
string ScopedTempDir::temp_dir_name_
The subdirectory name for our dir, or empty if it hasn't been set up.
Definition at line 95 of file test.h.
Referenced by Cleanup(), and CreateAndEnter().
The documentation for this struct was generated from the following files:
test.h
test.cc