Ninja: EdgeEnv Struct Reference
EdgeEnv Struct Reference
An Env for an Edge, providing $in and $out.
Public Member Functions
EdgeEnv (Edge *edge)
virtual string LookupVariable (const string &var)
string MakePathList (vector< Node * >::iterator begin, vector< Node * >::iterator end, char sep)
Given a span of Nodes, construct a list of paths suitable for a command line.
Public Attributes
Edge * edge_
Detailed Description
An Env for an Edge, providing $in and $out.
Definition at line 224 of file graph.cc.
Constructor & Destructor Documentation
EdgeEnv::EdgeEnv (Edge * edge) [inline, explicit]
Definition at line 225 of file graph.cc.
Member Function Documentation
string EdgeEnv::LookupVariable (const string & var) [virtual]
Implements Env.
Definition at line 237 of file graph.cc.
References edge_, Edge::env_, Rule::GetBinding(), Edge::implicit_deps_, Edge::inputs_, BindingEnv::LookupWithFallback(), MakePathList(), Edge::order_only_deps_, Edge::outputs_, and Edge::rule_.
Referenced by Edge::GetBinding().
string EdgeEnv::MakePathList (vector< Node * >::iterator begin, vector< Node * >::iterator end, char sep)
Given a span of Nodes, construct a list of paths suitable for a command line.
Definition at line 255 of file graph.cc.
Referenced by LookupVariable().
Member Data Documentation
Edge* EdgeEnv::edge_
Definition at line 234 of file graph.cc.
Referenced by LookupVariable().
The documentation for this struct was generated from the following file:
graph.cc