Ninja: ManifestParser Struct Reference
ManifestParser Struct Reference
Parses .ninja files.
#include <manifest_parser.h>
Classes
struct FileReader
Public Member Functions
bool Load (const string &filename, string *err, Lexer *parent=NULL)
Load and parse a file.
ManifestParser (State *state, FileReader *file_reader)
bool ParseTest (const string &input, string *err)
Parse a text string of input. Used by tests.
Private Member Functions
bool ExpectToken (Lexer::Token expected, string *err)
If the next token is not expected, produce an error string saying "expectd foo, got bar".
bool Parse (const string &filename, const string &input, string *err)
Parse a file, given its contents as a string.
bool ParseDefault (string *err)
bool ParseEdge (string *err)
bool ParseFileInclude (bool new_scope, string *err)
Parse either a 'subninja' or 'include' line.
bool ParseLet (string *key, EvalString *val, string *err)
bool ParsePool (string *err)
Parse various statement types.
bool ParseRule (string *err)
Private Attributes
BindingEnv * env_
FileReader * file_reader_
Lexer lexer_
State * state_
Detailed Description
Parses .ninja files.
Definition at line 29 of file manifest_parser.h.
Constructor & Destructor Documentation
ManifestParser::ManifestParser (State * state, FileReader * file_reader)
Definition at line 27 of file manifest_parser.cc.
References State::bindings_, and env_.
Member Function Documentation
bool ManifestParser::ExpectToken (Lexer::Token expected, string * err) [private]
If the next token is not expected, produce an error string saying "expectd foo, got bar".
Definition at line 372 of file manifest_parser.cc.
References Lexer::Error(), lexer_, Lexer::ReadToken(), Lexer::TokenErrorHint(), and Lexer::TokenName().
Referenced by ParseDefault(), ParseEdge(), ParseFileInclude(), ParseLet(), ParsePool(), and ParseRule().
bool ManifestParser::Load (const string & filename, string * err, Lexer * parent = NULL)
Load and parse a file.
Definition at line 32 of file manifest_parser.cc.
References Lexer::Error(), file_reader_, METRIC_RECORD, Parse(), and ManifestParser::FileReader::ReadFile().
Referenced by ParseFileInclude(), and TEST_F().
bool ManifestParser::Parse (const string & filename, const string & input, string * err) [private]
Parse a file, given its contents as a string.
Definition at line 53 of file manifest_parser.cc.
References BindingEnv::AddBinding(), Lexer::BUILD, CheckNinjaVersion(), Lexer::DEFAULT, Lexer::DescribeLastError(), env_, Lexer::ERROR, Lexer::Error(), EvalString::Evaluate(), Lexer::IDENT, Lexer::INCLUDE, lexer_, Lexer::NEWLINE, ParseDefault(), ParseEdge(), ParseFileInclude(), ParseLet(), ParsePool(), ParseRule(), Lexer::POOL, Lexer::ReadToken(), Lexer::RULE, Lexer::Start(), Lexer::SUBNINJA, Lexer::TEOF, Lexer::TokenName(), and Lexer::UnreadToken().
Referenced by Load().
bool ManifestParser::ParseDefault (string * err) [private]
Definition at line 202 of file manifest_parser.cc.
References State::AddDefault(), CanonicalizePath(), EvalString::Clear(), EvalString::empty(), env_, Lexer::Error(), EvalString::Evaluate(), ExpectToken(), lexer_, Lexer::NEWLINE, Lexer::ReadPath(), and state_.
Referenced by Parse().
bool ManifestParser::ParseEdge (string * err) [private]
Definition at line 228 of file manifest_parser.cc.
References BindingEnv::AddBinding(), State::AddEdge(), State::AddIn(), State::AddOut(), CanonicalizePath(), EvalString::Clear(), Lexer::COLON, EvalString::empty(), env_, Edge::env_, Lexer::Error(), EvalString::Evaluate(), ExpectToken(), Edge::GetBinding(), Edge::implicit_deps_, Lexer::INDENT, lexer_, State::LookupPool(), State::LookupRule(), Lexer::NEWLINE, Edge::order_only_deps_, Edge::outputs_, ParseLet(), Lexer::PeekToken(), Lexer::PIPE, Lexer::PIPE2, Edge::pool_, Lexer::ReadIdent(), Lexer::ReadPath(), and state_.
Referenced by Parse().
bool ManifestParser::ParseFileInclude (bool new_scope, string * err) [private]
Parse either a 'subninja' or 'include' line.
Definition at line 350 of file manifest_parser.cc.
References env_, EvalString::Evaluate(), ExpectToken(), file_reader_, lexer_, Load(), Lexer::NEWLINE, Lexer::ReadPath(), and state_.
Referenced by Parse().
bool ManifestParser::ParseLet (string * key, EvalString * val, string * err) [private]
Definition at line 192 of file manifest_parser.cc.
References Lexer::EQUALS, ExpectToken(), lexer_, Lexer::ReadIdent(), and Lexer::ReadVarValue().
Referenced by Parse(), ParseEdge(), ParsePool(), and ParseRule().
bool ManifestParser::ParsePool (string * err) [private]
Parse various statement types.
Definition at line 114 of file manifest_parser.cc.
References State::AddPool(), env_, Lexer::Error(), EvalString::Evaluate(), ExpectToken(), Lexer::INDENT, lexer_, State::LookupPool(), Lexer::NEWLINE, ParseLet(), Lexer::PeekToken(), Lexer::ReadIdent(), and state_.
Referenced by Parse().
bool ManifestParser::ParseRule (string * err) [private]
Definition at line 151 of file manifest_parser.cc.
References Rule::AddBinding(), State::AddRule(), Rule::bindings_, Lexer::Error(), ExpectToken(), Lexer::INDENT, Rule::IsReservedBinding(), lexer_, State::LookupRule(), Lexer::NEWLINE, ParseLet(), Lexer::PeekToken(), Lexer::ReadIdent(), and state_.
Referenced by Parse().
bool ManifestParser::ParseTest (const string & input, string * err) [inline]
Parse a text string of input. Used by tests.
Definition at line 41 of file manifest_parser.h.
Referenced by ParserTest::AssertParse(), AssertParse(), TEST_F(), and WriteTestData().
Member Data Documentation
BindingEnv* ManifestParser::env_ [private]
Definition at line 64 of file manifest_parser.h.
Referenced by ManifestParser(), Parse(), ParseDefault(), ParseEdge(), ParseFileInclude(), and ParsePool().
FileReader* ManifestParser::file_reader_ [private]
Definition at line 65 of file manifest_parser.h.
Referenced by Load(), and ParseFileInclude().
Lexer ManifestParser::lexer_ [private]
Definition at line 66 of file manifest_parser.h.
Referenced by ExpectToken(), Parse(), ParseDefault(), ParseEdge(), ParseFileInclude(), ParseLet(), ParsePool(), and ParseRule().
State* ManifestParser::state_ [private]
Definition at line 63 of file manifest_parser.h.
Referenced by ParseDefault(), ParseEdge(), ParseFileInclude(), ParsePool(), and ParseRule().
The documentation for this struct was generated from the following files:
manifest_parser.h
manifest_parser.cc