Ninja: BuildStatus::SlidingRateInfo Struct Reference
BuildStatus::SlidingRateInfo Struct Reference
Public Member Functions
double rate ()
void Restart ()
SlidingRateInfo (int n)
void UpdateRate (int update_hint)
Private Attributes
int last_update_
const size_t N
double rate_
Stopwatch stopwatch_
queue< double > times_
Detailed Description
Definition at line 252 of file build.h.
Constructor & Destructor Documentation
BuildStatus::SlidingRateInfo::SlidingRateInfo (int n) [inline]
Definition at line 253 of file build.h.
Member Function Documentation
double BuildStatus::SlidingRateInfo::rate () [inline]
Definition at line 256 of file build.h.
References rate_.
Referenced by BuildStatus::FormatProgressStatus().
void BuildStatus::SlidingRateInfo::Restart () [inline]
Definition at line 255 of file build.h.
References Stopwatch::Restart(), and stopwatch_.
Referenced by BuildStatus::PrintStatus().
void BuildStatus::SlidingRateInfo::UpdateRate (int update_hint) [inline]
Definition at line 258 of file build.h.
References Stopwatch::Elapsed(), last_update_, N, rate_, stopwatch_, and times_.
Referenced by BuildStatus::FormatProgressStatus().
Member Data Documentation
int BuildStatus::SlidingRateInfo::last_update_ [private]
Definition at line 275 of file build.h.
Referenced by UpdateRate().
const size_t BuildStatus::SlidingRateInfo::N [private]
Definition at line 273 of file build.h.
Referenced by UpdateRate().
double BuildStatus::SlidingRateInfo::rate_ [private]
Definition at line 271 of file build.h.
Referenced by rate(), and UpdateRate().
Stopwatch BuildStatus::SlidingRateInfo::stopwatch_ [private]
Definition at line 272 of file build.h.
Referenced by Restart(), and UpdateRate().
queue<double> BuildStatus::SlidingRateInfo::times_ [private]
Definition at line 274 of file build.h.
Referenced by UpdateRate().
The documentation for this struct was generated from the following file:
build.h