Ninja: Subprocess Struct Reference
Subprocess Struct Reference
Subprocess wraps a single async subprocess.
#include <subprocess.h>
Public Member Functions
bool Done () const
ExitStatus Finish ()
Returns ExitSuccess on successful process exit, ExitInterrupted if the process was interrupted, ExitFailure if it otherwise failed.
const string & GetOutput () const
~Subprocess ()
Private Member Functions
void OnPipeReady ()
bool Start (struct SubprocessSet *set, const string &command)
Subprocess (bool use_console)
Private Attributes
string buf_
int fd_
pid_t pid_
bool use_console_
Friends
struct SubprocessSet
Detailed Description
Subprocess wraps a single async subprocess.
It is entirely passive: it expects the caller to notify it when its fds are ready for reading, as well as call Finish() to reap the child once done() is true.
Definition at line 35 of file subprocess.h.
Constructor & Destructor Documentation
Subprocess::~Subprocess ()
Definition at line 31 of file subprocess-posix.cc.
References fd_, Finish(), and pid_.
Subprocess::Subprocess (bool use_console) [private]
Definition at line 28 of file subprocess-posix.cc.
Member Function Documentation
bool Subprocess::Done () const
Definition at line 139 of file subprocess-posix.cc.
References fd_.
Referenced by TEST_F().
ExitStatus Subprocess::Finish ()
Returns ExitSuccess on successful process exit, ExitInterrupted if the process was interrupted, ExitFailure if it otherwise failed.
Definition at line 121 of file subprocess-posix.cc.
References ExitFailure, ExitInterrupted, ExitSuccess, Fatal(), and pid_.
Referenced by TEST_F(), RealCommandRunner::WaitForCommand(), and ~Subprocess().
const string & Subprocess::GetOutput () const
Definition at line 143 of file subprocess-posix.cc.
References buf_.
Referenced by TEST_F(), and RealCommandRunner::WaitForCommand().
void Subprocess::OnPipeReady () [private]
Definition at line 108 of file subprocess-posix.cc.
References buf_, Fatal(), and fd_.
bool Subprocess::Start (struct SubprocessSet * set, const string & command) [private]
Definition at line 39 of file subprocess-posix.cc.
References Fatal(), fd_, pid_, SetCloseOnExec(), and use_console_.
Referenced by SubprocessSet::Add().
Friends And Related Function Documentation
friend struct SubprocessSet [friend]
Definition at line 69 of file subprocess.h.
Member Data Documentation
string Subprocess::buf_ [private]
Definition at line 51 of file subprocess.h.
Referenced by GetOutput(), and OnPipeReady().
int Subprocess::fd_ [private]
Definition at line 64 of file subprocess.h.
Referenced by Done(), OnPipeReady(), Start(), and ~Subprocess().
pid_t Subprocess::pid_ [private]
Definition at line 65 of file subprocess.h.
Referenced by Finish(), Start(), and ~Subprocess().
bool Subprocess::use_console_ [private]
Definition at line 67 of file subprocess.h.
Referenced by Start().
The documentation for this struct was generated from the following files:
subprocess.h
subprocess-posix.cc
subprocess-win32.cc