Ninja: Stopwatch Struct Reference
Stopwatch Struct Reference
A simple stopwatch which returns the time in seconds since Restart() was called.
#include <metrics.h>
Public Member Functions
double Elapsed () const
Seconds since Restart() call.
void Restart ()
Stopwatch ()
Private Member Functions
uint64_t Now () const
Private Attributes
uint64_t started_
Detailed Description
A simple stopwatch which returns the time in seconds since Restart() was called.
Definition at line 67 of file metrics.h.
Constructor & Destructor Documentation
Stopwatch::Stopwatch () [inline]
Definition at line 69 of file metrics.h.
Member Function Documentation
double Stopwatch::Elapsed () const [inline]
Seconds since Restart() call.
Definition at line 72 of file metrics.h.
Referenced by BuildStatus::RateInfo::Elapsed(), BuildStatus::RateInfo::UpdateRate(), and BuildStatus::SlidingRateInfo::UpdateRate().
uint64_t Stopwatch::Now () const [private]
Definition at line 118 of file metrics.cc.
void Stopwatch::Restart () [inline]
Definition at line 76 of file metrics.h.
Referenced by BuildStatus::RateInfo::Restart(), and BuildStatus::SlidingRateInfo::Restart().
Member Data Documentation
uint64_t Stopwatch::started_ [private]
Definition at line 79 of file metrics.h.
The documentation for this struct was generated from the following files:
metrics.h
metrics.cc