Ninja: GraphTest Struct Reference
GraphTest Struct Reference
Public Member Functions
void AddCatRule (State *state)
Add a "cat" rule to state.
Node * GetNode (const string &path)
Short way to get a Node by its path from state_.
GraphTest ()
Public Attributes
VirtualFileSystem fs_
DependencyScan scan_
State state_
Detailed Description
Definition at line 20 of file graph_test.cc.
Constructor & Destructor Documentation
GraphTest::GraphTest () [inline]
Definition at line 21 of file graph_test.cc.
Member Function Documentation
void StateTestWithBuiltinRules::AddCatRule (State * state) [inherited]
Add a "cat" rule to state.
Used by some tests; it's otherwise done by the ctor to state_.
Definition at line 80 of file test.cc.
References AssertParse().
Referenced by BuildTest::RebuildTarget(), and StateTestWithBuiltinRules::StateTestWithBuiltinRules().
Node * StateTestWithBuiltinRules::GetNode (const string & path) [inherited]
Short way to get a Node by its path from state_.
Definition at line 86 of file test.cc.
References State::GetNode(), and StateTestWithBuiltinRules::state_.
Referenced by BuildTest::Dirty(), and PlanTest::TestPoolWithDepthOne().
Member Data Documentation
VirtualFileSystem GraphTest::fs_
Definition at line 23 of file graph_test.cc.
DependencyScan GraphTest::scan_
Definition at line 24 of file graph_test.cc.
State StateTestWithBuiltinRules::state_ [inherited]
Definition at line 40 of file test.h.
Referenced by StateTestWithBuiltinRules::GetNode(), BuildTest::SetUp(), StateTestWithBuiltinRules::StateTestWithBuiltinRules(), and PlanTest::TestPoolWithDepthOne().
The documentation for this struct was generated from the following file:
graph_test.cc