Ninja: LaconicPrinter Struct Reference
LaconicPrinter Struct Reference
A test result printer that's less wordy than gtest's default.
Public Member Functions
LaconicPrinter ()
virtual void OnTestIterationStart (const testing::UnitTest &test_info, int iteration)
virtual void OnTestPartResult (const testing::TestPartResult &test_part_result)
virtual void OnTestProgramEnd (const testing::UnitTest &unit_test)
virtual void OnTestProgramStart (const testing::UnitTest &unit_test)
virtual void OnTestStart (const testing::TestInfo &test_info)
Private Attributes
int iteration_
LinePrinter printer_
int test_count_
int tests_started_
Detailed Description
A test result printer that's less wordy than gtest's default.
Definition at line 34 of file ninja_test.cc.
Constructor & Destructor Documentation
LaconicPrinter::LaconicPrinter () [inline]
Definition at line 35 of file ninja_test.cc.
Member Function Documentation
virtual void LaconicPrinter::OnTestIterationStart (const testing::UnitTest & test_info, int iteration) [inline, virtual]
Definition at line 40 of file ninja_test.cc.
References iteration_, and tests_started_.
virtual void LaconicPrinter::OnTestPartResult (const testing::TestPartResult & test_part_result) [inline, virtual]
Definition at line 59 of file ninja_test.cc.
References printer_, LinePrinter::PrintOnNewLine(), and StringPrintf().
virtual void LaconicPrinter::OnTestProgramEnd (const testing::UnitTest & unit_test) [inline, virtual]
Definition at line 68 of file ninja_test.cc.
References printer_, and LinePrinter::PrintOnNewLine().
virtual void LaconicPrinter::OnTestProgramStart (const testing::UnitTest & unit_test) [inline, virtual]
Definition at line 36 of file ninja_test.cc.
References test_count_.
virtual void LaconicPrinter::OnTestStart (const testing::TestInfo & test_info) [inline, virtual]
Definition at line 46 of file ninja_test.cc.
References LinePrinter::ELIDE, iteration_, LinePrinter::Print(), printer_, StringPrintf(), test_count_, and tests_started_.
Member Data Documentation
int LaconicPrinter::iteration_ [private]
Definition at line 76 of file ninja_test.cc.
Referenced by OnTestIterationStart(), and OnTestStart().
LinePrinter LaconicPrinter::printer_ [private]
Definition at line 73 of file ninja_test.cc.
Referenced by OnTestPartResult(), OnTestProgramEnd(), and OnTestStart().
int LaconicPrinter::test_count_ [private]
Definition at line 75 of file ninja_test.cc.
Referenced by OnTestProgramStart(), and OnTestStart().
int LaconicPrinter::tests_started_ [private]
Definition at line 74 of file ninja_test.cc.
Referenced by OnTestIterationStart(), and OnTestStart().
The documentation for this struct was generated from the following file:
ninja_test.cc