Ninja: subprocess_test.cc File Reference
subprocess_test.cc File Reference
#include "subprocess.h"
#include "test.h"
#include <sys/time.h>
#include <sys/resource.h>
#include <unistd.h>
Functions
TEST_F (SubprocessTest, BadCommandStderr)
TEST_F (SubprocessTest, NoSuchCommand)
TEST_F (SubprocessTest, InterruptChild)
TEST_F (SubprocessTest, InterruptParent)
TEST_F (SubprocessTest, SetWithSingle)
TEST_F (SubprocessTest, SetWithMulti)
TEST_F (SubprocessTest, SetWithLots)
TEST_F (SubprocessTest, ReadStdin)
Function Documentation
TEST_F (SubprocessTest , BadCommandStderr)
Definition at line 41 of file subprocess_test.cc.
References Subprocess::Done(), ExitFailure, Subprocess::Finish(), and Subprocess::GetOutput().
TEST_F (SubprocessTest , NoSuchCommand)
Definition at line 55 of file subprocess_test.cc.
References Subprocess::Done(), ExitFailure, Subprocess::Finish(), and Subprocess::GetOutput().
TEST_F (SubprocessTest , InterruptChild)
Definition at line 74 of file subprocess_test.cc.
References Subprocess::Done(), ExitInterrupted, and Subprocess::Finish().
TEST_F (SubprocessTest , InterruptParent)
Definition at line 85 of file subprocess_test.cc.
References Subprocess::Done().
TEST_F (SubprocessTest , SetWithSingle)
Definition at line 100 of file subprocess_test.cc.
References Subprocess::Done(), ExitSuccess, Subprocess::Finish(), and Subprocess::GetOutput().
TEST_F (SubprocessTest , SetWithMulti)
Definition at line 113 of file subprocess_test.cc.
References ExitSuccess.
TEST_F (SubprocessTest , SetWithLots)
Definition at line 156 of file subprocess_test.cc.
References ExitSuccess.
TEST_F (SubprocessTest , ReadStdin)
Definition at line 189 of file subprocess_test.cc.
References Subprocess::Done(), ExitSuccess, and Subprocess::Finish().