Ninja: test.h File Reference
test.h File Reference
#include <gtest/gtest.h>
#include "disk_interface.h"
#include "state.h"
#include "util.h"
Classes
struct VirtualFileSystem::Entry
An entry for a single in-memory file.
struct ScopedTempDir
struct StateTestWithBuiltinRules
A base test fixture that includes a State object with a builtin "cat" rule.
struct VirtualFileSystem
An implementation of DiskInterface that uses an in-memory representation of disk state.
Functions
void AssertHash (const char *expected, uint64_t actual)
void AssertParse (State *state, const char *input)
Function Documentation
void AssertHash (const char * expected, uint64_t actual)
Definition at line 97 of file test.cc.
References BuildLog::LogEntry::HashCommand().
Referenced by TEST_F().
void AssertParse (State * state, const char * input)
Definition at line 90 of file test.cc.
References ManifestParser::ParseTest().
Referenced by StateTestWithBuiltinRules::AddCatRule(), BuildTest::RebuildTarget(), BuildTest::SetUp(), TEST_F(), and PlanTest::TestPoolWithDepthOne().