Ninja: version.h File Reference
version.h File Reference
#include <string>
Functions
void CheckNinjaVersion (const string &required_version)
Check whether version is compatible with the current Ninja version, aborting if not.
void ParseVersion (const string &version, int *major, int *minor)
Parse the major/minor components of a version string.
Variables
const char * kNinjaVersion
The version number of the current Ninja release.
Function Documentation
void CheckNinjaVersion (const string & required_version)
Check whether version is compatible with the current Ninja version, aborting if not.
Definition at line 34 of file version.cc.
References Fatal(), kNinjaVersion, ParseVersion(), and Warning().
Referenced by ManifestParser::Parse().
void ParseVersion (const string & version, int * major, int * minor)
Parse the major/minor components of a version string.
Definition at line 23 of file version.cc.
Referenced by CheckNinjaVersion().
Variable Documentation
const char* kNinjaVersion
The version number of the current Ninja release.
This will always be "git" on trunk.
Definition at line 21 of file version.cc.
Referenced by CheckNinjaVersion().